// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVarianceDetailsUsingGETParams creates a new VarianceDetailsUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVarianceDetailsUsingGETParams() *VarianceDetailsUsingGETParams {
	return &VarianceDetailsUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVarianceDetailsUsingGETParamsWithTimeout creates a new VarianceDetailsUsingGETParams object
// with the ability to set a timeout on a request.
func NewVarianceDetailsUsingGETParamsWithTimeout(timeout time.Duration) *VarianceDetailsUsingGETParams {
	return &VarianceDetailsUsingGETParams{
		timeout: timeout,
	}
}

// NewVarianceDetailsUsingGETParamsWithContext creates a new VarianceDetailsUsingGETParams object
// with the ability to set a context for a request.
func NewVarianceDetailsUsingGETParamsWithContext(ctx context.Context) *VarianceDetailsUsingGETParams {
	return &VarianceDetailsUsingGETParams{
		Context: ctx,
	}
}

// NewVarianceDetailsUsingGETParamsWithHTTPClient creates a new VarianceDetailsUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewVarianceDetailsUsingGETParamsWithHTTPClient(client *http.Client) *VarianceDetailsUsingGETParams {
	return &VarianceDetailsUsingGETParams{
		HTTPClient: client,
	}
}

/*
VarianceDetailsUsingGETParams contains all the parameters to send to the API endpoint

	for the variance details using g e t operation.

	Typically these are written to a http.Request.
*/
type VarianceDetailsUsingGETParams struct {

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication string

	/* RequestUser.

	   requestUser
	*/
	RequestUser string

	/* TransactionReferenceNumber.

	   transactionReferenceNumber
	*/
	TransactionReferenceNumber string

	/* VarianceFormat.

	   varianceFormat
	*/
	VarianceFormat string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the variance details using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VarianceDetailsUsingGETParams) WithDefaults() *VarianceDetailsUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the variance details using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VarianceDetailsUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) WithTimeout(timeout time.Duration) *VarianceDetailsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) WithContext(ctx context.Context) *VarianceDetailsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) WithHTTPClient(client *http.Client) *VarianceDetailsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestApplication adds the requestApplication to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) WithRequestApplication(requestApplication string) *VarianceDetailsUsingGETParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) SetRequestApplication(requestApplication string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) WithRequestUser(requestUser string) *VarianceDetailsUsingGETParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) SetRequestUser(requestUser string) {
	o.RequestUser = requestUser
}

// WithTransactionReferenceNumber adds the transactionReferenceNumber to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) WithTransactionReferenceNumber(transactionReferenceNumber string) *VarianceDetailsUsingGETParams {
	o.SetTransactionReferenceNumber(transactionReferenceNumber)
	return o
}

// SetTransactionReferenceNumber adds the transactionReferenceNumber to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) SetTransactionReferenceNumber(transactionReferenceNumber string) {
	o.TransactionReferenceNumber = transactionReferenceNumber
}

// WithVarianceFormat adds the varianceFormat to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) WithVarianceFormat(varianceFormat string) *VarianceDetailsUsingGETParams {
	o.SetVarianceFormat(varianceFormat)
	return o
}

// SetVarianceFormat adds the varianceFormat to the variance details using g e t params
func (o *VarianceDetailsUsingGETParams) SetVarianceFormat(varianceFormat string) {
	o.VarianceFormat = varianceFormat
}

// WriteToRequest writes these params to a swagger request
func (o *VarianceDetailsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param requestApplication
	qrRequestApplication := o.RequestApplication
	qRequestApplication := qrRequestApplication
	if qRequestApplication != "" {

		if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
			return err
		}
	}

	// query param requestUser
	qrRequestUser := o.RequestUser
	qRequestUser := qrRequestUser
	if qRequestUser != "" {

		if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
			return err
		}
	}

	// query param transactionReferenceNumber
	qrTransactionReferenceNumber := o.TransactionReferenceNumber
	qTransactionReferenceNumber := qrTransactionReferenceNumber
	if qTransactionReferenceNumber != "" {

		if err := r.SetQueryParam("transactionReferenceNumber", qTransactionReferenceNumber); err != nil {
			return err
		}
	}

	// query param varianceFormat
	qrVarianceFormat := o.VarianceFormat
	qVarianceFormat := qrVarianceFormat
	if qVarianceFormat != "" {

		if err := r.SetQueryParam("varianceFormat", qVarianceFormat); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
