// Code generated by go-swagger; DO NOT EDIT.

package error

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHandlePutErrorUsingPUTParams creates a new HandlePutErrorUsingPUTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHandlePutErrorUsingPUTParams() *HandlePutErrorUsingPUTParams {
	return &HandlePutErrorUsingPUTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHandlePutErrorUsingPUTParamsWithTimeout creates a new HandlePutErrorUsingPUTParams object
// with the ability to set a timeout on a request.
func NewHandlePutErrorUsingPUTParamsWithTimeout(timeout time.Duration) *HandlePutErrorUsingPUTParams {
	return &HandlePutErrorUsingPUTParams{
		timeout: timeout,
	}
}

// NewHandlePutErrorUsingPUTParamsWithContext creates a new HandlePutErrorUsingPUTParams object
// with the ability to set a context for a request.
func NewHandlePutErrorUsingPUTParamsWithContext(ctx context.Context) *HandlePutErrorUsingPUTParams {
	return &HandlePutErrorUsingPUTParams{
		Context: ctx,
	}
}

// NewHandlePutErrorUsingPUTParamsWithHTTPClient creates a new HandlePutErrorUsingPUTParams object
// with the ability to set a custom HTTPClient for a request.
func NewHandlePutErrorUsingPUTParamsWithHTTPClient(client *http.Client) *HandlePutErrorUsingPUTParams {
	return &HandlePutErrorUsingPUTParams{
		HTTPClient: client,
	}
}

/*
HandlePutErrorUsingPUTParams contains all the parameters to send to the API endpoint

	for the handle put error using p u t operation.

	Typically these are written to a http.Request.
*/
type HandlePutErrorUsingPUTParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the handle put error using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandlePutErrorUsingPUTParams) WithDefaults() *HandlePutErrorUsingPUTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the handle put error using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandlePutErrorUsingPUTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the handle put error using p u t params
func (o *HandlePutErrorUsingPUTParams) WithTimeout(timeout time.Duration) *HandlePutErrorUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the handle put error using p u t params
func (o *HandlePutErrorUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the handle put error using p u t params
func (o *HandlePutErrorUsingPUTParams) WithContext(ctx context.Context) *HandlePutErrorUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the handle put error using p u t params
func (o *HandlePutErrorUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the handle put error using p u t params
func (o *HandlePutErrorUsingPUTParams) WithHTTPClient(client *http.Client) *HandlePutErrorUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the handle put error using p u t params
func (o *HandlePutErrorUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HandlePutErrorUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
