// Code generated by go-swagger; DO NOT EDIT.

package benefit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBenefitInfoUsingGETParams creates a new GetBenefitInfoUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBenefitInfoUsingGETParams() *GetBenefitInfoUsingGETParams {
	return &GetBenefitInfoUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBenefitInfoUsingGETParamsWithTimeout creates a new GetBenefitInfoUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetBenefitInfoUsingGETParamsWithTimeout(timeout time.Duration) *GetBenefitInfoUsingGETParams {
	return &GetBenefitInfoUsingGETParams{
		timeout: timeout,
	}
}

// NewGetBenefitInfoUsingGETParamsWithContext creates a new GetBenefitInfoUsingGETParams object
// with the ability to set a context for a request.
func NewGetBenefitInfoUsingGETParamsWithContext(ctx context.Context) *GetBenefitInfoUsingGETParams {
	return &GetBenefitInfoUsingGETParams{
		Context: ctx,
	}
}

// NewGetBenefitInfoUsingGETParamsWithHTTPClient creates a new GetBenefitInfoUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBenefitInfoUsingGETParamsWithHTTPClient(client *http.Client) *GetBenefitInfoUsingGETParams {
	return &GetBenefitInfoUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetBenefitInfoUsingGETParams contains all the parameters to send to the API endpoint

	for the get benefit info using g e t operation.

	Typically these are written to a http.Request.
*/
type GetBenefitInfoUsingGETParams struct {

	/* BenefitDescription.

	   benefitDescription
	*/
	BenefitDescription *string

	/* EffectiveDate.

	   effectiveDate
	*/
	EffectiveDate *string

	/* MemberGroupDescription.

	   memberGroupDescription
	*/
	MemberGroupDescription *string

	/* PolicyNumber.

	   policyNumber
	*/
	PolicyNumber *string

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication *string

	/* RequestUser.

	   requestUser
	*/
	RequestUser *string

	/* VarianceFormat.

	   varianceFormat
	*/
	VarianceFormat *string

	/* VarianceLevel.

	   varianceLevel
	*/
	VarianceLevel *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get benefit info using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBenefitInfoUsingGETParams) WithDefaults() *GetBenefitInfoUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get benefit info using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBenefitInfoUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithTimeout(timeout time.Duration) *GetBenefitInfoUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithContext(ctx context.Context) *GetBenefitInfoUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithHTTPClient(client *http.Client) *GetBenefitInfoUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBenefitDescription adds the benefitDescription to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithBenefitDescription(benefitDescription *string) *GetBenefitInfoUsingGETParams {
	o.SetBenefitDescription(benefitDescription)
	return o
}

// SetBenefitDescription adds the benefitDescription to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetBenefitDescription(benefitDescription *string) {
	o.BenefitDescription = benefitDescription
}

// WithEffectiveDate adds the effectiveDate to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithEffectiveDate(effectiveDate *string) *GetBenefitInfoUsingGETParams {
	o.SetEffectiveDate(effectiveDate)
	return o
}

// SetEffectiveDate adds the effectiveDate to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetEffectiveDate(effectiveDate *string) {
	o.EffectiveDate = effectiveDate
}

// WithMemberGroupDescription adds the memberGroupDescription to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithMemberGroupDescription(memberGroupDescription *string) *GetBenefitInfoUsingGETParams {
	o.SetMemberGroupDescription(memberGroupDescription)
	return o
}

// SetMemberGroupDescription adds the memberGroupDescription to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetMemberGroupDescription(memberGroupDescription *string) {
	o.MemberGroupDescription = memberGroupDescription
}

// WithPolicyNumber adds the policyNumber to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithPolicyNumber(policyNumber *string) *GetBenefitInfoUsingGETParams {
	o.SetPolicyNumber(policyNumber)
	return o
}

// SetPolicyNumber adds the policyNumber to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetPolicyNumber(policyNumber *string) {
	o.PolicyNumber = policyNumber
}

// WithRequestApplication adds the requestApplication to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithRequestApplication(requestApplication *string) *GetBenefitInfoUsingGETParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetRequestApplication(requestApplication *string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithRequestUser(requestUser *string) *GetBenefitInfoUsingGETParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetRequestUser(requestUser *string) {
	o.RequestUser = requestUser
}

// WithVarianceFormat adds the varianceFormat to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithVarianceFormat(varianceFormat *string) *GetBenefitInfoUsingGETParams {
	o.SetVarianceFormat(varianceFormat)
	return o
}

// SetVarianceFormat adds the varianceFormat to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetVarianceFormat(varianceFormat *string) {
	o.VarianceFormat = varianceFormat
}

// WithVarianceLevel adds the varianceLevel to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) WithVarianceLevel(varianceLevel *string) *GetBenefitInfoUsingGETParams {
	o.SetVarianceLevel(varianceLevel)
	return o
}

// SetVarianceLevel adds the varianceLevel to the get benefit info using g e t params
func (o *GetBenefitInfoUsingGETParams) SetVarianceLevel(varianceLevel *string) {
	o.VarianceLevel = varianceLevel
}

// WriteToRequest writes these params to a swagger request
func (o *GetBenefitInfoUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BenefitDescription != nil {

		// query param benefitDescription
		var qrBenefitDescription string

		if o.BenefitDescription != nil {
			qrBenefitDescription = *o.BenefitDescription
		}
		qBenefitDescription := qrBenefitDescription
		if qBenefitDescription != "" {

			if err := r.SetQueryParam("benefitDescription", qBenefitDescription); err != nil {
				return err
			}
		}
	}

	if o.EffectiveDate != nil {

		// query param effectiveDate
		var qrEffectiveDate string

		if o.EffectiveDate != nil {
			qrEffectiveDate = *o.EffectiveDate
		}
		qEffectiveDate := qrEffectiveDate
		if qEffectiveDate != "" {

			if err := r.SetQueryParam("effectiveDate", qEffectiveDate); err != nil {
				return err
			}
		}
	}

	if o.MemberGroupDescription != nil {

		// query param memberGroupDescription
		var qrMemberGroupDescription string

		if o.MemberGroupDescription != nil {
			qrMemberGroupDescription = *o.MemberGroupDescription
		}
		qMemberGroupDescription := qrMemberGroupDescription
		if qMemberGroupDescription != "" {

			if err := r.SetQueryParam("memberGroupDescription", qMemberGroupDescription); err != nil {
				return err
			}
		}
	}

	if o.PolicyNumber != nil {

		// query param policyNumber
		var qrPolicyNumber string

		if o.PolicyNumber != nil {
			qrPolicyNumber = *o.PolicyNumber
		}
		qPolicyNumber := qrPolicyNumber
		if qPolicyNumber != "" {

			if err := r.SetQueryParam("policyNumber", qPolicyNumber); err != nil {
				return err
			}
		}
	}

	if o.RequestApplication != nil {

		// query param requestApplication
		var qrRequestApplication string

		if o.RequestApplication != nil {
			qrRequestApplication = *o.RequestApplication
		}
		qRequestApplication := qrRequestApplication
		if qRequestApplication != "" {

			if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
				return err
			}
		}
	}

	if o.RequestUser != nil {

		// query param requestUser
		var qrRequestUser string

		if o.RequestUser != nil {
			qrRequestUser = *o.RequestUser
		}
		qRequestUser := qrRequestUser
		if qRequestUser != "" {

			if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
				return err
			}
		}
	}

	if o.VarianceFormat != nil {

		// query param varianceFormat
		var qrVarianceFormat string

		if o.VarianceFormat != nil {
			qrVarianceFormat = *o.VarianceFormat
		}
		qVarianceFormat := qrVarianceFormat
		if qVarianceFormat != "" {

			if err := r.SetQueryParam("varianceFormat", qVarianceFormat); err != nil {
				return err
			}
		}
	}

	if o.VarianceLevel != nil {

		// query param varianceLevel
		var qrVarianceLevel string

		if o.VarianceLevel != nil {
			qrVarianceLevel = *o.VarianceLevel
		}
		qVarianceLevel := qrVarianceLevel
		if qVarianceLevel != "" {

			if err := r.SetQueryParam("varianceLevel", qVarianceLevel); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
