// Code generated by go-swagger; DO NOT EDIT.

package dependent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateLastNameUsingPUTParams creates a new UpdateLastNameUsingPUTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateLastNameUsingPUTParams() *UpdateLastNameUsingPUTParams {
	return &UpdateLastNameUsingPUTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateLastNameUsingPUTParamsWithTimeout creates a new UpdateLastNameUsingPUTParams object
// with the ability to set a timeout on a request.
func NewUpdateLastNameUsingPUTParamsWithTimeout(timeout time.Duration) *UpdateLastNameUsingPUTParams {
	return &UpdateLastNameUsingPUTParams{
		timeout: timeout,
	}
}

// NewUpdateLastNameUsingPUTParamsWithContext creates a new UpdateLastNameUsingPUTParams object
// with the ability to set a context for a request.
func NewUpdateLastNameUsingPUTParamsWithContext(ctx context.Context) *UpdateLastNameUsingPUTParams {
	return &UpdateLastNameUsingPUTParams{
		Context: ctx,
	}
}

// NewUpdateLastNameUsingPUTParamsWithHTTPClient creates a new UpdateLastNameUsingPUTParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateLastNameUsingPUTParamsWithHTTPClient(client *http.Client) *UpdateLastNameUsingPUTParams {
	return &UpdateLastNameUsingPUTParams{
		HTTPClient: client,
	}
}

/*
UpdateLastNameUsingPUTParams contains all the parameters to send to the API endpoint

	for the update last name using p u t operation.

	Typically these are written to a http.Request.
*/
type UpdateLastNameUsingPUTParams struct {

	/* CaseMemberKey.

	   caseMemberKey
	*/
	CaseMemberKey *string

	/* DependentClientID.

	   dependentClientId
	*/
	DependentClientID *string

	/* EffectiveDate.

	   effectiveDate
	*/
	EffectiveDate *string

	/* LastName.

	   lastName
	*/
	LastName string

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication *string

	/* RequestUser.

	   requestUser
	*/
	RequestUser *string

	/* VarianceFormat.

	   varianceFormat
	*/
	VarianceFormat *string

	/* VarianceLevel.

	   varianceLevel
	*/
	VarianceLevel *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update last name using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateLastNameUsingPUTParams) WithDefaults() *UpdateLastNameUsingPUTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update last name using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateLastNameUsingPUTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithTimeout(timeout time.Duration) *UpdateLastNameUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithContext(ctx context.Context) *UpdateLastNameUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithHTTPClient(client *http.Client) *UpdateLastNameUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCaseMemberKey adds the caseMemberKey to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithCaseMemberKey(caseMemberKey *string) *UpdateLastNameUsingPUTParams {
	o.SetCaseMemberKey(caseMemberKey)
	return o
}

// SetCaseMemberKey adds the caseMemberKey to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetCaseMemberKey(caseMemberKey *string) {
	o.CaseMemberKey = caseMemberKey
}

// WithDependentClientID adds the dependentClientID to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithDependentClientID(dependentClientID *string) *UpdateLastNameUsingPUTParams {
	o.SetDependentClientID(dependentClientID)
	return o
}

// SetDependentClientID adds the dependentClientId to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetDependentClientID(dependentClientID *string) {
	o.DependentClientID = dependentClientID
}

// WithEffectiveDate adds the effectiveDate to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithEffectiveDate(effectiveDate *string) *UpdateLastNameUsingPUTParams {
	o.SetEffectiveDate(effectiveDate)
	return o
}

// SetEffectiveDate adds the effectiveDate to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetEffectiveDate(effectiveDate *string) {
	o.EffectiveDate = effectiveDate
}

// WithLastName adds the lastName to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithLastName(lastName string) *UpdateLastNameUsingPUTParams {
	o.SetLastName(lastName)
	return o
}

// SetLastName adds the lastName to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetLastName(lastName string) {
	o.LastName = lastName
}

// WithRequestApplication adds the requestApplication to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithRequestApplication(requestApplication *string) *UpdateLastNameUsingPUTParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetRequestApplication(requestApplication *string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithRequestUser(requestUser *string) *UpdateLastNameUsingPUTParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetRequestUser(requestUser *string) {
	o.RequestUser = requestUser
}

// WithVarianceFormat adds the varianceFormat to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithVarianceFormat(varianceFormat *string) *UpdateLastNameUsingPUTParams {
	o.SetVarianceFormat(varianceFormat)
	return o
}

// SetVarianceFormat adds the varianceFormat to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetVarianceFormat(varianceFormat *string) {
	o.VarianceFormat = varianceFormat
}

// WithVarianceLevel adds the varianceLevel to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) WithVarianceLevel(varianceLevel *string) *UpdateLastNameUsingPUTParams {
	o.SetVarianceLevel(varianceLevel)
	return o
}

// SetVarianceLevel adds the varianceLevel to the update last name using p u t params
func (o *UpdateLastNameUsingPUTParams) SetVarianceLevel(varianceLevel *string) {
	o.VarianceLevel = varianceLevel
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateLastNameUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CaseMemberKey != nil {

		// query param caseMemberKey
		var qrCaseMemberKey string

		if o.CaseMemberKey != nil {
			qrCaseMemberKey = *o.CaseMemberKey
		}
		qCaseMemberKey := qrCaseMemberKey
		if qCaseMemberKey != "" {

			if err := r.SetQueryParam("caseMemberKey", qCaseMemberKey); err != nil {
				return err
			}
		}
	}

	if o.DependentClientID != nil {

		// query param dependentClientId
		var qrDependentClientID string

		if o.DependentClientID != nil {
			qrDependentClientID = *o.DependentClientID
		}
		qDependentClientID := qrDependentClientID
		if qDependentClientID != "" {

			if err := r.SetQueryParam("dependentClientId", qDependentClientID); err != nil {
				return err
			}
		}
	}

	if o.EffectiveDate != nil {

		// query param effectiveDate
		var qrEffectiveDate string

		if o.EffectiveDate != nil {
			qrEffectiveDate = *o.EffectiveDate
		}
		qEffectiveDate := qrEffectiveDate
		if qEffectiveDate != "" {

			if err := r.SetQueryParam("effectiveDate", qEffectiveDate); err != nil {
				return err
			}
		}
	}
	if err := r.SetBodyParam(o.LastName); err != nil {
		return err
	}

	if o.RequestApplication != nil {

		// query param requestApplication
		var qrRequestApplication string

		if o.RequestApplication != nil {
			qrRequestApplication = *o.RequestApplication
		}
		qRequestApplication := qrRequestApplication
		if qRequestApplication != "" {

			if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
				return err
			}
		}
	}

	if o.RequestUser != nil {

		// query param requestUser
		var qrRequestUser string

		if o.RequestUser != nil {
			qrRequestUser = *o.RequestUser
		}
		qRequestUser := qrRequestUser
		if qRequestUser != "" {

			if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
				return err
			}
		}
	}

	if o.VarianceFormat != nil {

		// query param varianceFormat
		var qrVarianceFormat string

		if o.VarianceFormat != nil {
			qrVarianceFormat = *o.VarianceFormat
		}
		qVarianceFormat := qrVarianceFormat
		if qVarianceFormat != "" {

			if err := r.SetQueryParam("varianceFormat", qVarianceFormat); err != nil {
				return err
			}
		}
	}

	if o.VarianceLevel != nil {

		// query param varianceLevel
		var qrVarianceLevel string

		if o.VarianceLevel != nil {
			qrVarianceLevel = *o.VarianceLevel
		}
		qVarianceLevel := qrVarianceLevel
		if qVarianceLevel != "" {

			if err := r.SetQueryParam("varianceLevel", qVarianceLevel); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
