// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgencyIDDTO AgencyIdDTO
//
// swagger:model AgencyIdDTO
type AgencyIDDTO struct {

	// agency key
	AgencyKey string `json:"agencyKey,omitempty"`

	// agency number
	AgencyNumber string `json:"agencyNumber,omitempty"`
}

// Validate validates this agency Id d t o
func (m *AgencyIDDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agency Id d t o based on context it is used
func (m *AgencyIDDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgencyIDDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgencyIDDTO) UnmarshalBinary(b []byte) error {
	var res AgencyIDDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
