// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMemberBenefitOptionUsingGETParams creates a new GetMemberBenefitOptionUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMemberBenefitOptionUsingGETParams() *GetMemberBenefitOptionUsingGETParams {
	return &GetMemberBenefitOptionUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMemberBenefitOptionUsingGETParamsWithTimeout creates a new GetMemberBenefitOptionUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetMemberBenefitOptionUsingGETParamsWithTimeout(timeout time.Duration) *GetMemberBenefitOptionUsingGETParams {
	return &GetMemberBenefitOptionUsingGETParams{
		timeout: timeout,
	}
}

// NewGetMemberBenefitOptionUsingGETParamsWithContext creates a new GetMemberBenefitOptionUsingGETParams object
// with the ability to set a context for a request.
func NewGetMemberBenefitOptionUsingGETParamsWithContext(ctx context.Context) *GetMemberBenefitOptionUsingGETParams {
	return &GetMemberBenefitOptionUsingGETParams{
		Context: ctx,
	}
}

// NewGetMemberBenefitOptionUsingGETParamsWithHTTPClient creates a new GetMemberBenefitOptionUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMemberBenefitOptionUsingGETParamsWithHTTPClient(client *http.Client) *GetMemberBenefitOptionUsingGETParams {
	return &GetMemberBenefitOptionUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetMemberBenefitOptionUsingGETParams contains all the parameters to send to the API endpoint

	for the get member benefit option using g e t operation.

	Typically these are written to a http.Request.
*/
type GetMemberBenefitOptionUsingGETParams struct {

	/* BenefitParentDescription.

	   benefitParentDescription
	*/
	BenefitParentDescription *string

	/* EffectiveDate.

	   effectiveDate
	*/
	EffectiveDate *string

	/* MemberGroupDescription.

	   memberGroupDescription
	*/
	MemberGroupDescription *string

	/* MemberNumber.

	   memberNumber
	*/
	MemberNumber *string

	/* PolicyNumber.

	   policyNumber
	*/
	PolicyNumber *string

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication *string

	/* RequestUser.

	   requestUser
	*/
	RequestUser *string

	/* VarianceFormat.

	   varianceFormat
	*/
	VarianceFormat *string

	/* VarianceLevel.

	   varianceLevel
	*/
	VarianceLevel *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get member benefit option using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMemberBenefitOptionUsingGETParams) WithDefaults() *GetMemberBenefitOptionUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get member benefit option using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMemberBenefitOptionUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithTimeout(timeout time.Duration) *GetMemberBenefitOptionUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithContext(ctx context.Context) *GetMemberBenefitOptionUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithHTTPClient(client *http.Client) *GetMemberBenefitOptionUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBenefitParentDescription adds the benefitParentDescription to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithBenefitParentDescription(benefitParentDescription *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetBenefitParentDescription(benefitParentDescription)
	return o
}

// SetBenefitParentDescription adds the benefitParentDescription to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetBenefitParentDescription(benefitParentDescription *string) {
	o.BenefitParentDescription = benefitParentDescription
}

// WithEffectiveDate adds the effectiveDate to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithEffectiveDate(effectiveDate *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetEffectiveDate(effectiveDate)
	return o
}

// SetEffectiveDate adds the effectiveDate to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetEffectiveDate(effectiveDate *string) {
	o.EffectiveDate = effectiveDate
}

// WithMemberGroupDescription adds the memberGroupDescription to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithMemberGroupDescription(memberGroupDescription *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetMemberGroupDescription(memberGroupDescription)
	return o
}

// SetMemberGroupDescription adds the memberGroupDescription to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetMemberGroupDescription(memberGroupDescription *string) {
	o.MemberGroupDescription = memberGroupDescription
}

// WithMemberNumber adds the memberNumber to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithMemberNumber(memberNumber *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetMemberNumber(memberNumber)
	return o
}

// SetMemberNumber adds the memberNumber to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetMemberNumber(memberNumber *string) {
	o.MemberNumber = memberNumber
}

// WithPolicyNumber adds the policyNumber to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithPolicyNumber(policyNumber *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetPolicyNumber(policyNumber)
	return o
}

// SetPolicyNumber adds the policyNumber to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetPolicyNumber(policyNumber *string) {
	o.PolicyNumber = policyNumber
}

// WithRequestApplication adds the requestApplication to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithRequestApplication(requestApplication *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetRequestApplication(requestApplication *string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithRequestUser(requestUser *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetRequestUser(requestUser *string) {
	o.RequestUser = requestUser
}

// WithVarianceFormat adds the varianceFormat to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithVarianceFormat(varianceFormat *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetVarianceFormat(varianceFormat)
	return o
}

// SetVarianceFormat adds the varianceFormat to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetVarianceFormat(varianceFormat *string) {
	o.VarianceFormat = varianceFormat
}

// WithVarianceLevel adds the varianceLevel to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) WithVarianceLevel(varianceLevel *string) *GetMemberBenefitOptionUsingGETParams {
	o.SetVarianceLevel(varianceLevel)
	return o
}

// SetVarianceLevel adds the varianceLevel to the get member benefit option using g e t params
func (o *GetMemberBenefitOptionUsingGETParams) SetVarianceLevel(varianceLevel *string) {
	o.VarianceLevel = varianceLevel
}

// WriteToRequest writes these params to a swagger request
func (o *GetMemberBenefitOptionUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BenefitParentDescription != nil {

		// query param benefitParentDescription
		var qrBenefitParentDescription string

		if o.BenefitParentDescription != nil {
			qrBenefitParentDescription = *o.BenefitParentDescription
		}
		qBenefitParentDescription := qrBenefitParentDescription
		if qBenefitParentDescription != "" {

			if err := r.SetQueryParam("benefitParentDescription", qBenefitParentDescription); err != nil {
				return err
			}
		}
	}

	if o.EffectiveDate != nil {

		// query param effectiveDate
		var qrEffectiveDate string

		if o.EffectiveDate != nil {
			qrEffectiveDate = *o.EffectiveDate
		}
		qEffectiveDate := qrEffectiveDate
		if qEffectiveDate != "" {

			if err := r.SetQueryParam("effectiveDate", qEffectiveDate); err != nil {
				return err
			}
		}
	}

	if o.MemberGroupDescription != nil {

		// query param memberGroupDescription
		var qrMemberGroupDescription string

		if o.MemberGroupDescription != nil {
			qrMemberGroupDescription = *o.MemberGroupDescription
		}
		qMemberGroupDescription := qrMemberGroupDescription
		if qMemberGroupDescription != "" {

			if err := r.SetQueryParam("memberGroupDescription", qMemberGroupDescription); err != nil {
				return err
			}
		}
	}

	if o.MemberNumber != nil {

		// query param memberNumber
		var qrMemberNumber string

		if o.MemberNumber != nil {
			qrMemberNumber = *o.MemberNumber
		}
		qMemberNumber := qrMemberNumber
		if qMemberNumber != "" {

			if err := r.SetQueryParam("memberNumber", qMemberNumber); err != nil {
				return err
			}
		}
	}

	if o.PolicyNumber != nil {

		// query param policyNumber
		var qrPolicyNumber string

		if o.PolicyNumber != nil {
			qrPolicyNumber = *o.PolicyNumber
		}
		qPolicyNumber := qrPolicyNumber
		if qPolicyNumber != "" {

			if err := r.SetQueryParam("policyNumber", qPolicyNumber); err != nil {
				return err
			}
		}
	}

	if o.RequestApplication != nil {

		// query param requestApplication
		var qrRequestApplication string

		if o.RequestApplication != nil {
			qrRequestApplication = *o.RequestApplication
		}
		qRequestApplication := qrRequestApplication
		if qRequestApplication != "" {

			if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
				return err
			}
		}
	}

	if o.RequestUser != nil {

		// query param requestUser
		var qrRequestUser string

		if o.RequestUser != nil {
			qrRequestUser = *o.RequestUser
		}
		qRequestUser := qrRequestUser
		if qRequestUser != "" {

			if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
				return err
			}
		}
	}

	if o.VarianceFormat != nil {

		// query param varianceFormat
		var qrVarianceFormat string

		if o.VarianceFormat != nil {
			qrVarianceFormat = *o.VarianceFormat
		}
		qVarianceFormat := qrVarianceFormat
		if qVarianceFormat != "" {

			if err := r.SetQueryParam("varianceFormat", qVarianceFormat); err != nil {
				return err
			}
		}
	}

	if o.VarianceLevel != nil {

		// query param varianceLevel
		var qrVarianceLevel string

		if o.VarianceLevel != nil {
			qrVarianceLevel = *o.VarianceLevel
		}
		qVarianceLevel := qrVarianceLevel
		if qVarianceLevel != "" {

			if err := r.SetQueryParam("varianceLevel", qVarianceLevel); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
