// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"client/models"
)

// GetMemberListCensusV2UsingGETReader is a Reader for the GetMemberListCensusV2UsingGET structure.
type GetMemberListCensusV2UsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMemberListCensusV2UsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMemberListCensusV2UsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMemberListCensusV2UsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetMemberListCensusV2UsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetMemberListCensusV2UsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMemberListCensusV2UsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetMemberListCensusV2UsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /compassintegrationapp/member/censusSearch] getMemberListCensusV2UsingGET", response, response.Code())
	}
}

// NewGetMemberListCensusV2UsingGETOK creates a GetMemberListCensusV2UsingGETOK with default headers values
func NewGetMemberListCensusV2UsingGETOK() *GetMemberListCensusV2UsingGETOK {
	return &GetMemberListCensusV2UsingGETOK{}
}

/*
GetMemberListCensusV2UsingGETOK describes a response with status code 200, with default header values.

Success
*/
type GetMemberListCensusV2UsingGETOK struct {
	Payload *models.ResponseWrapperMemberListDTO
}

// IsSuccess returns true when this get member list census v2 using g e t o k response has a 2xx status code
func (o *GetMemberListCensusV2UsingGETOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get member list census v2 using g e t o k response has a 3xx status code
func (o *GetMemberListCensusV2UsingGETOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member list census v2 using g e t o k response has a 4xx status code
func (o *GetMemberListCensusV2UsingGETOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get member list census v2 using g e t o k response has a 5xx status code
func (o *GetMemberListCensusV2UsingGETOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get member list census v2 using g e t o k response a status code equal to that given
func (o *GetMemberListCensusV2UsingGETOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get member list census v2 using g e t o k response
func (o *GetMemberListCensusV2UsingGETOK) Code() int {
	return 200
}

func (o *GetMemberListCensusV2UsingGETOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETOK %s", 200, payload)
}

func (o *GetMemberListCensusV2UsingGETOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETOK %s", 200, payload)
}

func (o *GetMemberListCensusV2UsingGETOK) GetPayload() *models.ResponseWrapperMemberListDTO {
	return o.Payload
}

func (o *GetMemberListCensusV2UsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperMemberListDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMemberListCensusV2UsingGETBadRequest creates a GetMemberListCensusV2UsingGETBadRequest with default headers values
func NewGetMemberListCensusV2UsingGETBadRequest() *GetMemberListCensusV2UsingGETBadRequest {
	return &GetMemberListCensusV2UsingGETBadRequest{}
}

/*
GetMemberListCensusV2UsingGETBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetMemberListCensusV2UsingGETBadRequest struct {
}

// IsSuccess returns true when this get member list census v2 using g e t bad request response has a 2xx status code
func (o *GetMemberListCensusV2UsingGETBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member list census v2 using g e t bad request response has a 3xx status code
func (o *GetMemberListCensusV2UsingGETBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member list census v2 using g e t bad request response has a 4xx status code
func (o *GetMemberListCensusV2UsingGETBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member list census v2 using g e t bad request response has a 5xx status code
func (o *GetMemberListCensusV2UsingGETBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get member list census v2 using g e t bad request response a status code equal to that given
func (o *GetMemberListCensusV2UsingGETBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get member list census v2 using g e t bad request response
func (o *GetMemberListCensusV2UsingGETBadRequest) Code() int {
	return 400
}

func (o *GetMemberListCensusV2UsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETBadRequest", 400)
}

func (o *GetMemberListCensusV2UsingGETBadRequest) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETBadRequest", 400)
}

func (o *GetMemberListCensusV2UsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberListCensusV2UsingGETUnauthorized creates a GetMemberListCensusV2UsingGETUnauthorized with default headers values
func NewGetMemberListCensusV2UsingGETUnauthorized() *GetMemberListCensusV2UsingGETUnauthorized {
	return &GetMemberListCensusV2UsingGETUnauthorized{}
}

/*
GetMemberListCensusV2UsingGETUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetMemberListCensusV2UsingGETUnauthorized struct {
}

// IsSuccess returns true when this get member list census v2 using g e t unauthorized response has a 2xx status code
func (o *GetMemberListCensusV2UsingGETUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member list census v2 using g e t unauthorized response has a 3xx status code
func (o *GetMemberListCensusV2UsingGETUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member list census v2 using g e t unauthorized response has a 4xx status code
func (o *GetMemberListCensusV2UsingGETUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member list census v2 using g e t unauthorized response has a 5xx status code
func (o *GetMemberListCensusV2UsingGETUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get member list census v2 using g e t unauthorized response a status code equal to that given
func (o *GetMemberListCensusV2UsingGETUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get member list census v2 using g e t unauthorized response
func (o *GetMemberListCensusV2UsingGETUnauthorized) Code() int {
	return 401
}

func (o *GetMemberListCensusV2UsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETUnauthorized", 401)
}

func (o *GetMemberListCensusV2UsingGETUnauthorized) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETUnauthorized", 401)
}

func (o *GetMemberListCensusV2UsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberListCensusV2UsingGETForbidden creates a GetMemberListCensusV2UsingGETForbidden with default headers values
func NewGetMemberListCensusV2UsingGETForbidden() *GetMemberListCensusV2UsingGETForbidden {
	return &GetMemberListCensusV2UsingGETForbidden{}
}

/*
GetMemberListCensusV2UsingGETForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetMemberListCensusV2UsingGETForbidden struct {
}

// IsSuccess returns true when this get member list census v2 using g e t forbidden response has a 2xx status code
func (o *GetMemberListCensusV2UsingGETForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member list census v2 using g e t forbidden response has a 3xx status code
func (o *GetMemberListCensusV2UsingGETForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member list census v2 using g e t forbidden response has a 4xx status code
func (o *GetMemberListCensusV2UsingGETForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member list census v2 using g e t forbidden response has a 5xx status code
func (o *GetMemberListCensusV2UsingGETForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get member list census v2 using g e t forbidden response a status code equal to that given
func (o *GetMemberListCensusV2UsingGETForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get member list census v2 using g e t forbidden response
func (o *GetMemberListCensusV2UsingGETForbidden) Code() int {
	return 403
}

func (o *GetMemberListCensusV2UsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETForbidden", 403)
}

func (o *GetMemberListCensusV2UsingGETForbidden) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETForbidden", 403)
}

func (o *GetMemberListCensusV2UsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberListCensusV2UsingGETNotFound creates a GetMemberListCensusV2UsingGETNotFound with default headers values
func NewGetMemberListCensusV2UsingGETNotFound() *GetMemberListCensusV2UsingGETNotFound {
	return &GetMemberListCensusV2UsingGETNotFound{}
}

/*
GetMemberListCensusV2UsingGETNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetMemberListCensusV2UsingGETNotFound struct {
}

// IsSuccess returns true when this get member list census v2 using g e t not found response has a 2xx status code
func (o *GetMemberListCensusV2UsingGETNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member list census v2 using g e t not found response has a 3xx status code
func (o *GetMemberListCensusV2UsingGETNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member list census v2 using g e t not found response has a 4xx status code
func (o *GetMemberListCensusV2UsingGETNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member list census v2 using g e t not found response has a 5xx status code
func (o *GetMemberListCensusV2UsingGETNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get member list census v2 using g e t not found response a status code equal to that given
func (o *GetMemberListCensusV2UsingGETNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get member list census v2 using g e t not found response
func (o *GetMemberListCensusV2UsingGETNotFound) Code() int {
	return 404
}

func (o *GetMemberListCensusV2UsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETNotFound", 404)
}

func (o *GetMemberListCensusV2UsingGETNotFound) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETNotFound", 404)
}

func (o *GetMemberListCensusV2UsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberListCensusV2UsingGETInternalServerError creates a GetMemberListCensusV2UsingGETInternalServerError with default headers values
func NewGetMemberListCensusV2UsingGETInternalServerError() *GetMemberListCensusV2UsingGETInternalServerError {
	return &GetMemberListCensusV2UsingGETInternalServerError{}
}

/*
GetMemberListCensusV2UsingGETInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type GetMemberListCensusV2UsingGETInternalServerError struct {
}

// IsSuccess returns true when this get member list census v2 using g e t internal server error response has a 2xx status code
func (o *GetMemberListCensusV2UsingGETInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member list census v2 using g e t internal server error response has a 3xx status code
func (o *GetMemberListCensusV2UsingGETInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member list census v2 using g e t internal server error response has a 4xx status code
func (o *GetMemberListCensusV2UsingGETInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get member list census v2 using g e t internal server error response has a 5xx status code
func (o *GetMemberListCensusV2UsingGETInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get member list census v2 using g e t internal server error response a status code equal to that given
func (o *GetMemberListCensusV2UsingGETInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get member list census v2 using g e t internal server error response
func (o *GetMemberListCensusV2UsingGETInternalServerError) Code() int {
	return 500
}

func (o *GetMemberListCensusV2UsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETInternalServerError", 500)
}

func (o *GetMemberListCensusV2UsingGETInternalServerError) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/member/censusSearch][%d] getMemberListCensusV2UsingGETInternalServerError", 500)
}

func (o *GetMemberListCensusV2UsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
