// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExpireAssociatedCompensationEntitiesUsingPUTParams creates a new ExpireAssociatedCompensationEntitiesUsingPUTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExpireAssociatedCompensationEntitiesUsingPUTParams() *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	return &ExpireAssociatedCompensationEntitiesUsingPUTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExpireAssociatedCompensationEntitiesUsingPUTParamsWithTimeout creates a new ExpireAssociatedCompensationEntitiesUsingPUTParams object
// with the ability to set a timeout on a request.
func NewExpireAssociatedCompensationEntitiesUsingPUTParamsWithTimeout(timeout time.Duration) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	return &ExpireAssociatedCompensationEntitiesUsingPUTParams{
		timeout: timeout,
	}
}

// NewExpireAssociatedCompensationEntitiesUsingPUTParamsWithContext creates a new ExpireAssociatedCompensationEntitiesUsingPUTParams object
// with the ability to set a context for a request.
func NewExpireAssociatedCompensationEntitiesUsingPUTParamsWithContext(ctx context.Context) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	return &ExpireAssociatedCompensationEntitiesUsingPUTParams{
		Context: ctx,
	}
}

// NewExpireAssociatedCompensationEntitiesUsingPUTParamsWithHTTPClient creates a new ExpireAssociatedCompensationEntitiesUsingPUTParams object
// with the ability to set a custom HTTPClient for a request.
func NewExpireAssociatedCompensationEntitiesUsingPUTParamsWithHTTPClient(client *http.Client) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	return &ExpireAssociatedCompensationEntitiesUsingPUTParams{
		HTTPClient: client,
	}
}

/*
ExpireAssociatedCompensationEntitiesUsingPUTParams contains all the parameters to send to the API endpoint

	for the expire associated compensation entities using p u t operation.

	Typically these are written to a http.Request.
*/
type ExpireAssociatedCompensationEntitiesUsingPUTParams struct {

	/* CommissionRuleKey.

	   commissionRuleKey
	*/
	CommissionRuleKey *string

	/* CompensationType.

	   compensationType
	*/
	CompensationType string

	/* ExpirationDate.

	   expirationDate
	*/
	ExpirationDate *string

	/* PolicyNumber.

	   policyNumber
	*/
	PolicyNumber *string

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication *string

	/* RequestUser.

	   requestUser
	*/
	RequestUser *string

	/* VarianceFormat.

	   varianceFormat
	*/
	VarianceFormat *string

	/* VarianceLevel.

	   varianceLevel
	*/
	VarianceLevel *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the expire associated compensation entities using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithDefaults() *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the expire associated compensation entities using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithTimeout(timeout time.Duration) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithContext(ctx context.Context) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithHTTPClient(client *http.Client) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommissionRuleKey adds the commissionRuleKey to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithCommissionRuleKey(commissionRuleKey *string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetCommissionRuleKey(commissionRuleKey)
	return o
}

// SetCommissionRuleKey adds the commissionRuleKey to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetCommissionRuleKey(commissionRuleKey *string) {
	o.CommissionRuleKey = commissionRuleKey
}

// WithCompensationType adds the compensationType to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithCompensationType(compensationType string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetCompensationType(compensationType)
	return o
}

// SetCompensationType adds the compensationType to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetCompensationType(compensationType string) {
	o.CompensationType = compensationType
}

// WithExpirationDate adds the expirationDate to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithExpirationDate(expirationDate *string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetExpirationDate(expirationDate)
	return o
}

// SetExpirationDate adds the expirationDate to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetExpirationDate(expirationDate *string) {
	o.ExpirationDate = expirationDate
}

// WithPolicyNumber adds the policyNumber to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithPolicyNumber(policyNumber *string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetPolicyNumber(policyNumber)
	return o
}

// SetPolicyNumber adds the policyNumber to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetPolicyNumber(policyNumber *string) {
	o.PolicyNumber = policyNumber
}

// WithRequestApplication adds the requestApplication to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithRequestApplication(requestApplication *string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetRequestApplication(requestApplication *string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithRequestUser(requestUser *string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetRequestUser(requestUser *string) {
	o.RequestUser = requestUser
}

// WithVarianceFormat adds the varianceFormat to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithVarianceFormat(varianceFormat *string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetVarianceFormat(varianceFormat)
	return o
}

// SetVarianceFormat adds the varianceFormat to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetVarianceFormat(varianceFormat *string) {
	o.VarianceFormat = varianceFormat
}

// WithVarianceLevel adds the varianceLevel to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WithVarianceLevel(varianceLevel *string) *ExpireAssociatedCompensationEntitiesUsingPUTParams {
	o.SetVarianceLevel(varianceLevel)
	return o
}

// SetVarianceLevel adds the varianceLevel to the expire associated compensation entities using p u t params
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) SetVarianceLevel(varianceLevel *string) {
	o.VarianceLevel = varianceLevel
}

// WriteToRequest writes these params to a swagger request
func (o *ExpireAssociatedCompensationEntitiesUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CommissionRuleKey != nil {

		// query param commissionRuleKey
		var qrCommissionRuleKey string

		if o.CommissionRuleKey != nil {
			qrCommissionRuleKey = *o.CommissionRuleKey
		}
		qCommissionRuleKey := qrCommissionRuleKey
		if qCommissionRuleKey != "" {

			if err := r.SetQueryParam("commissionRuleKey", qCommissionRuleKey); err != nil {
				return err
			}
		}
	}
	if err := r.SetBodyParam(o.CompensationType); err != nil {
		return err
	}

	if o.ExpirationDate != nil {

		// query param expirationDate
		var qrExpirationDate string

		if o.ExpirationDate != nil {
			qrExpirationDate = *o.ExpirationDate
		}
		qExpirationDate := qrExpirationDate
		if qExpirationDate != "" {

			if err := r.SetQueryParam("expirationDate", qExpirationDate); err != nil {
				return err
			}
		}
	}

	if o.PolicyNumber != nil {

		// query param policyNumber
		var qrPolicyNumber string

		if o.PolicyNumber != nil {
			qrPolicyNumber = *o.PolicyNumber
		}
		qPolicyNumber := qrPolicyNumber
		if qPolicyNumber != "" {

			if err := r.SetQueryParam("policyNumber", qPolicyNumber); err != nil {
				return err
			}
		}
	}

	if o.RequestApplication != nil {

		// query param requestApplication
		var qrRequestApplication string

		if o.RequestApplication != nil {
			qrRequestApplication = *o.RequestApplication
		}
		qRequestApplication := qrRequestApplication
		if qRequestApplication != "" {

			if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
				return err
			}
		}
	}

	if o.RequestUser != nil {

		// query param requestUser
		var qrRequestUser string

		if o.RequestUser != nil {
			qrRequestUser = *o.RequestUser
		}
		qRequestUser := qrRequestUser
		if qRequestUser != "" {

			if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
				return err
			}
		}
	}

	if o.VarianceFormat != nil {

		// query param varianceFormat
		var qrVarianceFormat string

		if o.VarianceFormat != nil {
			qrVarianceFormat = *o.VarianceFormat
		}
		qVarianceFormat := qrVarianceFormat
		if qVarianceFormat != "" {

			if err := r.SetQueryParam("varianceFormat", qVarianceFormat); err != nil {
				return err
			}
		}
	}

	if o.VarianceLevel != nil {

		// query param varianceLevel
		var qrVarianceLevel string

		if o.VarianceLevel != nil {
			qrVarianceLevel = *o.VarianceLevel
		}
		qVarianceLevel := qrVarianceLevel
		if qVarianceLevel != "" {

			if err := r.SetQueryParam("varianceLevel", qVarianceLevel); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
