// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"client/models"
)

// GetMemberGroupBenefitOptionsUsingGETReader is a Reader for the GetMemberGroupBenefitOptionsUsingGET structure.
type GetMemberGroupBenefitOptionsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMemberGroupBenefitOptionsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMemberGroupBenefitOptionsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMemberGroupBenefitOptionsUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetMemberGroupBenefitOptionsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetMemberGroupBenefitOptionsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMemberGroupBenefitOptionsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetMemberGroupBenefitOptionsUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /compassintegrationapp/policy/memberGroupBenefitOptions] getMemberGroupBenefitOptionsUsingGET", response, response.Code())
	}
}

// NewGetMemberGroupBenefitOptionsUsingGETOK creates a GetMemberGroupBenefitOptionsUsingGETOK with default headers values
func NewGetMemberGroupBenefitOptionsUsingGETOK() *GetMemberGroupBenefitOptionsUsingGETOK {
	return &GetMemberGroupBenefitOptionsUsingGETOK{}
}

/*
GetMemberGroupBenefitOptionsUsingGETOK describes a response with status code 200, with default header values.

Success
*/
type GetMemberGroupBenefitOptionsUsingGETOK struct {
	Payload *models.ResponseWrapperMapStringListMemberGroupBenefitOptionDTO
}

// IsSuccess returns true when this get member group benefit options using g e t o k response has a 2xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get member group benefit options using g e t o k response has a 3xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member group benefit options using g e t o k response has a 4xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get member group benefit options using g e t o k response has a 5xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get member group benefit options using g e t o k response a status code equal to that given
func (o *GetMemberGroupBenefitOptionsUsingGETOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get member group benefit options using g e t o k response
func (o *GetMemberGroupBenefitOptionsUsingGETOK) Code() int {
	return 200
}

func (o *GetMemberGroupBenefitOptionsUsingGETOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETOK %s", 200, payload)
}

func (o *GetMemberGroupBenefitOptionsUsingGETOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETOK %s", 200, payload)
}

func (o *GetMemberGroupBenefitOptionsUsingGETOK) GetPayload() *models.ResponseWrapperMapStringListMemberGroupBenefitOptionDTO {
	return o.Payload
}

func (o *GetMemberGroupBenefitOptionsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperMapStringListMemberGroupBenefitOptionDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMemberGroupBenefitOptionsUsingGETBadRequest creates a GetMemberGroupBenefitOptionsUsingGETBadRequest with default headers values
func NewGetMemberGroupBenefitOptionsUsingGETBadRequest() *GetMemberGroupBenefitOptionsUsingGETBadRequest {
	return &GetMemberGroupBenefitOptionsUsingGETBadRequest{}
}

/*
GetMemberGroupBenefitOptionsUsingGETBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetMemberGroupBenefitOptionsUsingGETBadRequest struct {
}

// IsSuccess returns true when this get member group benefit options using g e t bad request response has a 2xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member group benefit options using g e t bad request response has a 3xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member group benefit options using g e t bad request response has a 4xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member group benefit options using g e t bad request response has a 5xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get member group benefit options using g e t bad request response a status code equal to that given
func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get member group benefit options using g e t bad request response
func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) Code() int {
	return 400
}

func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETBadRequest", 400)
}

func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETBadRequest", 400)
}

func (o *GetMemberGroupBenefitOptionsUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberGroupBenefitOptionsUsingGETUnauthorized creates a GetMemberGroupBenefitOptionsUsingGETUnauthorized with default headers values
func NewGetMemberGroupBenefitOptionsUsingGETUnauthorized() *GetMemberGroupBenefitOptionsUsingGETUnauthorized {
	return &GetMemberGroupBenefitOptionsUsingGETUnauthorized{}
}

/*
GetMemberGroupBenefitOptionsUsingGETUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetMemberGroupBenefitOptionsUsingGETUnauthorized struct {
}

// IsSuccess returns true when this get member group benefit options using g e t unauthorized response has a 2xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member group benefit options using g e t unauthorized response has a 3xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member group benefit options using g e t unauthorized response has a 4xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member group benefit options using g e t unauthorized response has a 5xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get member group benefit options using g e t unauthorized response a status code equal to that given
func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get member group benefit options using g e t unauthorized response
func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) Code() int {
	return 401
}

func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETUnauthorized", 401)
}

func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETUnauthorized", 401)
}

func (o *GetMemberGroupBenefitOptionsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberGroupBenefitOptionsUsingGETForbidden creates a GetMemberGroupBenefitOptionsUsingGETForbidden with default headers values
func NewGetMemberGroupBenefitOptionsUsingGETForbidden() *GetMemberGroupBenefitOptionsUsingGETForbidden {
	return &GetMemberGroupBenefitOptionsUsingGETForbidden{}
}

/*
GetMemberGroupBenefitOptionsUsingGETForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetMemberGroupBenefitOptionsUsingGETForbidden struct {
}

// IsSuccess returns true when this get member group benefit options using g e t forbidden response has a 2xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member group benefit options using g e t forbidden response has a 3xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member group benefit options using g e t forbidden response has a 4xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member group benefit options using g e t forbidden response has a 5xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get member group benefit options using g e t forbidden response a status code equal to that given
func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get member group benefit options using g e t forbidden response
func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) Code() int {
	return 403
}

func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETForbidden", 403)
}

func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETForbidden", 403)
}

func (o *GetMemberGroupBenefitOptionsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberGroupBenefitOptionsUsingGETNotFound creates a GetMemberGroupBenefitOptionsUsingGETNotFound with default headers values
func NewGetMemberGroupBenefitOptionsUsingGETNotFound() *GetMemberGroupBenefitOptionsUsingGETNotFound {
	return &GetMemberGroupBenefitOptionsUsingGETNotFound{}
}

/*
GetMemberGroupBenefitOptionsUsingGETNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetMemberGroupBenefitOptionsUsingGETNotFound struct {
}

// IsSuccess returns true when this get member group benefit options using g e t not found response has a 2xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member group benefit options using g e t not found response has a 3xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member group benefit options using g e t not found response has a 4xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get member group benefit options using g e t not found response has a 5xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get member group benefit options using g e t not found response a status code equal to that given
func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get member group benefit options using g e t not found response
func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) Code() int {
	return 404
}

func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETNotFound", 404)
}

func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETNotFound", 404)
}

func (o *GetMemberGroupBenefitOptionsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberGroupBenefitOptionsUsingGETInternalServerError creates a GetMemberGroupBenefitOptionsUsingGETInternalServerError with default headers values
func NewGetMemberGroupBenefitOptionsUsingGETInternalServerError() *GetMemberGroupBenefitOptionsUsingGETInternalServerError {
	return &GetMemberGroupBenefitOptionsUsingGETInternalServerError{}
}

/*
GetMemberGroupBenefitOptionsUsingGETInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type GetMemberGroupBenefitOptionsUsingGETInternalServerError struct {
}

// IsSuccess returns true when this get member group benefit options using g e t internal server error response has a 2xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get member group benefit options using g e t internal server error response has a 3xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get member group benefit options using g e t internal server error response has a 4xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get member group benefit options using g e t internal server error response has a 5xx status code
func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get member group benefit options using g e t internal server error response a status code equal to that given
func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get member group benefit options using g e t internal server error response
func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) Code() int {
	return 500
}

func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETInternalServerError", 500)
}

func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) String() string {
	return fmt.Sprintf("[GET /compassintegrationapp/policy/memberGroupBenefitOptions][%d] getMemberGroupBenefitOptionsUsingGETInternalServerError", 500)
}

func (o *GetMemberGroupBenefitOptionsUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
