// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPayrollAliasUsingGETParams creates a new PayrollAliasUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPayrollAliasUsingGETParams() *PayrollAliasUsingGETParams {
	return &PayrollAliasUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPayrollAliasUsingGETParamsWithTimeout creates a new PayrollAliasUsingGETParams object
// with the ability to set a timeout on a request.
func NewPayrollAliasUsingGETParamsWithTimeout(timeout time.Duration) *PayrollAliasUsingGETParams {
	return &PayrollAliasUsingGETParams{
		timeout: timeout,
	}
}

// NewPayrollAliasUsingGETParamsWithContext creates a new PayrollAliasUsingGETParams object
// with the ability to set a context for a request.
func NewPayrollAliasUsingGETParamsWithContext(ctx context.Context) *PayrollAliasUsingGETParams {
	return &PayrollAliasUsingGETParams{
		Context: ctx,
	}
}

// NewPayrollAliasUsingGETParamsWithHTTPClient creates a new PayrollAliasUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewPayrollAliasUsingGETParamsWithHTTPClient(client *http.Client) *PayrollAliasUsingGETParams {
	return &PayrollAliasUsingGETParams{
		HTTPClient: client,
	}
}

/*
PayrollAliasUsingGETParams contains all the parameters to send to the API endpoint

	for the payroll alias using g e t operation.

	Typically these are written to a http.Request.
*/
type PayrollAliasUsingGETParams struct {

	/* EffectiveDate.

	   effectiveDate
	*/
	EffectiveDate *string

	/* PolicyNumber.

	   policyNumber
	*/
	PolicyNumber *string

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication *string

	/* RequestUser.

	   requestUser
	*/
	RequestUser *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the payroll alias using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PayrollAliasUsingGETParams) WithDefaults() *PayrollAliasUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the payroll alias using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PayrollAliasUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) WithTimeout(timeout time.Duration) *PayrollAliasUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) WithContext(ctx context.Context) *PayrollAliasUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) WithHTTPClient(client *http.Client) *PayrollAliasUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEffectiveDate adds the effectiveDate to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) WithEffectiveDate(effectiveDate *string) *PayrollAliasUsingGETParams {
	o.SetEffectiveDate(effectiveDate)
	return o
}

// SetEffectiveDate adds the effectiveDate to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) SetEffectiveDate(effectiveDate *string) {
	o.EffectiveDate = effectiveDate
}

// WithPolicyNumber adds the policyNumber to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) WithPolicyNumber(policyNumber *string) *PayrollAliasUsingGETParams {
	o.SetPolicyNumber(policyNumber)
	return o
}

// SetPolicyNumber adds the policyNumber to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) SetPolicyNumber(policyNumber *string) {
	o.PolicyNumber = policyNumber
}

// WithRequestApplication adds the requestApplication to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) WithRequestApplication(requestApplication *string) *PayrollAliasUsingGETParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) SetRequestApplication(requestApplication *string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) WithRequestUser(requestUser *string) *PayrollAliasUsingGETParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the payroll alias using g e t params
func (o *PayrollAliasUsingGETParams) SetRequestUser(requestUser *string) {
	o.RequestUser = requestUser
}

// WriteToRequest writes these params to a swagger request
func (o *PayrollAliasUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EffectiveDate != nil {

		// query param effectiveDate
		var qrEffectiveDate string

		if o.EffectiveDate != nil {
			qrEffectiveDate = *o.EffectiveDate
		}
		qEffectiveDate := qrEffectiveDate
		if qEffectiveDate != "" {

			if err := r.SetQueryParam("effectiveDate", qEffectiveDate); err != nil {
				return err
			}
		}
	}

	if o.PolicyNumber != nil {

		// query param policyNumber
		var qrPolicyNumber string

		if o.PolicyNumber != nil {
			qrPolicyNumber = *o.PolicyNumber
		}
		qPolicyNumber := qrPolicyNumber
		if qPolicyNumber != "" {

			if err := r.SetQueryParam("policyNumber", qPolicyNumber); err != nil {
				return err
			}
		}
	}

	if o.RequestApplication != nil {

		// query param requestApplication
		var qrRequestApplication string

		if o.RequestApplication != nil {
			qrRequestApplication = *o.RequestApplication
		}
		qRequestApplication := qrRequestApplication
		if qRequestApplication != "" {

			if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
				return err
			}
		}
	}

	if o.RequestUser != nil {

		// query param requestUser
		var qrRequestUser string

		if o.RequestUser != nil {
			qrRequestUser = *o.RequestUser
		}
		qRequestUser := qrRequestUser
		if qRequestUser != "" {

			if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
