// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"client/models"
)

// ProcessRenewalPeriodUsingPUTReader is a Reader for the ProcessRenewalPeriodUsingPUT structure.
type ProcessRenewalPeriodUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProcessRenewalPeriodUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProcessRenewalPeriodUsingPUTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewProcessRenewalPeriodUsingPUTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewProcessRenewalPeriodUsingPUTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewProcessRenewalPeriodUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewProcessRenewalPeriodUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewProcessRenewalPeriodUsingPUTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewProcessRenewalPeriodUsingPUTInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /compassintegrationapp/policy/processRenewalPeriod] processRenewalPeriodUsingPUT", response, response.Code())
	}
}

// NewProcessRenewalPeriodUsingPUTOK creates a ProcessRenewalPeriodUsingPUTOK with default headers values
func NewProcessRenewalPeriodUsingPUTOK() *ProcessRenewalPeriodUsingPUTOK {
	return &ProcessRenewalPeriodUsingPUTOK{}
}

/*
ProcessRenewalPeriodUsingPUTOK describes a response with status code 200, with default header values.

Success
*/
type ProcessRenewalPeriodUsingPUTOK struct {
	Payload *models.ResponseWrapperBoolean
}

// IsSuccess returns true when this process renewal period using p u t o k response has a 2xx status code
func (o *ProcessRenewalPeriodUsingPUTOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this process renewal period using p u t o k response has a 3xx status code
func (o *ProcessRenewalPeriodUsingPUTOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this process renewal period using p u t o k response has a 4xx status code
func (o *ProcessRenewalPeriodUsingPUTOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this process renewal period using p u t o k response has a 5xx status code
func (o *ProcessRenewalPeriodUsingPUTOK) IsServerError() bool {
	return false
}

// IsCode returns true when this process renewal period using p u t o k response a status code equal to that given
func (o *ProcessRenewalPeriodUsingPUTOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the process renewal period using p u t o k response
func (o *ProcessRenewalPeriodUsingPUTOK) Code() int {
	return 200
}

func (o *ProcessRenewalPeriodUsingPUTOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTOK %s", 200, payload)
}

func (o *ProcessRenewalPeriodUsingPUTOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTOK %s", 200, payload)
}

func (o *ProcessRenewalPeriodUsingPUTOK) GetPayload() *models.ResponseWrapperBoolean {
	return o.Payload
}

func (o *ProcessRenewalPeriodUsingPUTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperBoolean)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProcessRenewalPeriodUsingPUTCreated creates a ProcessRenewalPeriodUsingPUTCreated with default headers values
func NewProcessRenewalPeriodUsingPUTCreated() *ProcessRenewalPeriodUsingPUTCreated {
	return &ProcessRenewalPeriodUsingPUTCreated{}
}

/*
ProcessRenewalPeriodUsingPUTCreated describes a response with status code 201, with default header values.

Created
*/
type ProcessRenewalPeriodUsingPUTCreated struct {
}

// IsSuccess returns true when this process renewal period using p u t created response has a 2xx status code
func (o *ProcessRenewalPeriodUsingPUTCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this process renewal period using p u t created response has a 3xx status code
func (o *ProcessRenewalPeriodUsingPUTCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this process renewal period using p u t created response has a 4xx status code
func (o *ProcessRenewalPeriodUsingPUTCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this process renewal period using p u t created response has a 5xx status code
func (o *ProcessRenewalPeriodUsingPUTCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this process renewal period using p u t created response a status code equal to that given
func (o *ProcessRenewalPeriodUsingPUTCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the process renewal period using p u t created response
func (o *ProcessRenewalPeriodUsingPUTCreated) Code() int {
	return 201
}

func (o *ProcessRenewalPeriodUsingPUTCreated) Error() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTCreated", 201)
}

func (o *ProcessRenewalPeriodUsingPUTCreated) String() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTCreated", 201)
}

func (o *ProcessRenewalPeriodUsingPUTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProcessRenewalPeriodUsingPUTBadRequest creates a ProcessRenewalPeriodUsingPUTBadRequest with default headers values
func NewProcessRenewalPeriodUsingPUTBadRequest() *ProcessRenewalPeriodUsingPUTBadRequest {
	return &ProcessRenewalPeriodUsingPUTBadRequest{}
}

/*
ProcessRenewalPeriodUsingPUTBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ProcessRenewalPeriodUsingPUTBadRequest struct {
}

// IsSuccess returns true when this process renewal period using p u t bad request response has a 2xx status code
func (o *ProcessRenewalPeriodUsingPUTBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this process renewal period using p u t bad request response has a 3xx status code
func (o *ProcessRenewalPeriodUsingPUTBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this process renewal period using p u t bad request response has a 4xx status code
func (o *ProcessRenewalPeriodUsingPUTBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this process renewal period using p u t bad request response has a 5xx status code
func (o *ProcessRenewalPeriodUsingPUTBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this process renewal period using p u t bad request response a status code equal to that given
func (o *ProcessRenewalPeriodUsingPUTBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the process renewal period using p u t bad request response
func (o *ProcessRenewalPeriodUsingPUTBadRequest) Code() int {
	return 400
}

func (o *ProcessRenewalPeriodUsingPUTBadRequest) Error() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTBadRequest", 400)
}

func (o *ProcessRenewalPeriodUsingPUTBadRequest) String() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTBadRequest", 400)
}

func (o *ProcessRenewalPeriodUsingPUTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProcessRenewalPeriodUsingPUTUnauthorized creates a ProcessRenewalPeriodUsingPUTUnauthorized with default headers values
func NewProcessRenewalPeriodUsingPUTUnauthorized() *ProcessRenewalPeriodUsingPUTUnauthorized {
	return &ProcessRenewalPeriodUsingPUTUnauthorized{}
}

/*
ProcessRenewalPeriodUsingPUTUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ProcessRenewalPeriodUsingPUTUnauthorized struct {
}

// IsSuccess returns true when this process renewal period using p u t unauthorized response has a 2xx status code
func (o *ProcessRenewalPeriodUsingPUTUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this process renewal period using p u t unauthorized response has a 3xx status code
func (o *ProcessRenewalPeriodUsingPUTUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this process renewal period using p u t unauthorized response has a 4xx status code
func (o *ProcessRenewalPeriodUsingPUTUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this process renewal period using p u t unauthorized response has a 5xx status code
func (o *ProcessRenewalPeriodUsingPUTUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this process renewal period using p u t unauthorized response a status code equal to that given
func (o *ProcessRenewalPeriodUsingPUTUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the process renewal period using p u t unauthorized response
func (o *ProcessRenewalPeriodUsingPUTUnauthorized) Code() int {
	return 401
}

func (o *ProcessRenewalPeriodUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTUnauthorized", 401)
}

func (o *ProcessRenewalPeriodUsingPUTUnauthorized) String() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTUnauthorized", 401)
}

func (o *ProcessRenewalPeriodUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProcessRenewalPeriodUsingPUTForbidden creates a ProcessRenewalPeriodUsingPUTForbidden with default headers values
func NewProcessRenewalPeriodUsingPUTForbidden() *ProcessRenewalPeriodUsingPUTForbidden {
	return &ProcessRenewalPeriodUsingPUTForbidden{}
}

/*
ProcessRenewalPeriodUsingPUTForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ProcessRenewalPeriodUsingPUTForbidden struct {
}

// IsSuccess returns true when this process renewal period using p u t forbidden response has a 2xx status code
func (o *ProcessRenewalPeriodUsingPUTForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this process renewal period using p u t forbidden response has a 3xx status code
func (o *ProcessRenewalPeriodUsingPUTForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this process renewal period using p u t forbidden response has a 4xx status code
func (o *ProcessRenewalPeriodUsingPUTForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this process renewal period using p u t forbidden response has a 5xx status code
func (o *ProcessRenewalPeriodUsingPUTForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this process renewal period using p u t forbidden response a status code equal to that given
func (o *ProcessRenewalPeriodUsingPUTForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the process renewal period using p u t forbidden response
func (o *ProcessRenewalPeriodUsingPUTForbidden) Code() int {
	return 403
}

func (o *ProcessRenewalPeriodUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTForbidden", 403)
}

func (o *ProcessRenewalPeriodUsingPUTForbidden) String() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTForbidden", 403)
}

func (o *ProcessRenewalPeriodUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProcessRenewalPeriodUsingPUTNotFound creates a ProcessRenewalPeriodUsingPUTNotFound with default headers values
func NewProcessRenewalPeriodUsingPUTNotFound() *ProcessRenewalPeriodUsingPUTNotFound {
	return &ProcessRenewalPeriodUsingPUTNotFound{}
}

/*
ProcessRenewalPeriodUsingPUTNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ProcessRenewalPeriodUsingPUTNotFound struct {
}

// IsSuccess returns true when this process renewal period using p u t not found response has a 2xx status code
func (o *ProcessRenewalPeriodUsingPUTNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this process renewal period using p u t not found response has a 3xx status code
func (o *ProcessRenewalPeriodUsingPUTNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this process renewal period using p u t not found response has a 4xx status code
func (o *ProcessRenewalPeriodUsingPUTNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this process renewal period using p u t not found response has a 5xx status code
func (o *ProcessRenewalPeriodUsingPUTNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this process renewal period using p u t not found response a status code equal to that given
func (o *ProcessRenewalPeriodUsingPUTNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the process renewal period using p u t not found response
func (o *ProcessRenewalPeriodUsingPUTNotFound) Code() int {
	return 404
}

func (o *ProcessRenewalPeriodUsingPUTNotFound) Error() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTNotFound", 404)
}

func (o *ProcessRenewalPeriodUsingPUTNotFound) String() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTNotFound", 404)
}

func (o *ProcessRenewalPeriodUsingPUTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProcessRenewalPeriodUsingPUTInternalServerError creates a ProcessRenewalPeriodUsingPUTInternalServerError with default headers values
func NewProcessRenewalPeriodUsingPUTInternalServerError() *ProcessRenewalPeriodUsingPUTInternalServerError {
	return &ProcessRenewalPeriodUsingPUTInternalServerError{}
}

/*
ProcessRenewalPeriodUsingPUTInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type ProcessRenewalPeriodUsingPUTInternalServerError struct {
}

// IsSuccess returns true when this process renewal period using p u t internal server error response has a 2xx status code
func (o *ProcessRenewalPeriodUsingPUTInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this process renewal period using p u t internal server error response has a 3xx status code
func (o *ProcessRenewalPeriodUsingPUTInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this process renewal period using p u t internal server error response has a 4xx status code
func (o *ProcessRenewalPeriodUsingPUTInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this process renewal period using p u t internal server error response has a 5xx status code
func (o *ProcessRenewalPeriodUsingPUTInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this process renewal period using p u t internal server error response a status code equal to that given
func (o *ProcessRenewalPeriodUsingPUTInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the process renewal period using p u t internal server error response
func (o *ProcessRenewalPeriodUsingPUTInternalServerError) Code() int {
	return 500
}

func (o *ProcessRenewalPeriodUsingPUTInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTInternalServerError", 500)
}

func (o *ProcessRenewalPeriodUsingPUTInternalServerError) String() string {
	return fmt.Sprintf("[PUT /compassintegrationapp/policy/processRenewalPeriod][%d] processRenewalPeriodUsingPUTInternalServerError", 500)
}

func (o *ProcessRenewalPeriodUsingPUTInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
