// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateBenefitOptionListDescriptionUsingPOSTParams creates a new UpdateBenefitOptionListDescriptionUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateBenefitOptionListDescriptionUsingPOSTParams() *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	return &UpdateBenefitOptionListDescriptionUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateBenefitOptionListDescriptionUsingPOSTParamsWithTimeout creates a new UpdateBenefitOptionListDescriptionUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewUpdateBenefitOptionListDescriptionUsingPOSTParamsWithTimeout(timeout time.Duration) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	return &UpdateBenefitOptionListDescriptionUsingPOSTParams{
		timeout: timeout,
	}
}

// NewUpdateBenefitOptionListDescriptionUsingPOSTParamsWithContext creates a new UpdateBenefitOptionListDescriptionUsingPOSTParams object
// with the ability to set a context for a request.
func NewUpdateBenefitOptionListDescriptionUsingPOSTParamsWithContext(ctx context.Context) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	return &UpdateBenefitOptionListDescriptionUsingPOSTParams{
		Context: ctx,
	}
}

// NewUpdateBenefitOptionListDescriptionUsingPOSTParamsWithHTTPClient creates a new UpdateBenefitOptionListDescriptionUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateBenefitOptionListDescriptionUsingPOSTParamsWithHTTPClient(client *http.Client) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	return &UpdateBenefitOptionListDescriptionUsingPOSTParams{
		HTTPClient: client,
	}
}

/*
UpdateBenefitOptionListDescriptionUsingPOSTParams contains all the parameters to send to the API endpoint

	for the update benefit option list description using p o s t operation.

	Typically these are written to a http.Request.
*/
type UpdateBenefitOptionListDescriptionUsingPOSTParams struct {

	/* EffectiveDate.

	   effectiveDate
	*/
	EffectiveDate *string

	/* NewChoiceListDescription.

	   newChoiceListDescription
	*/
	NewChoiceListDescription *string

	/* OldChoiceListDescription.

	   oldChoiceListDescription
	*/
	OldChoiceListDescription *string

	/* PolicyNumber.

	   policyNumber
	*/
	PolicyNumber *string

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication *string

	/* RequestUser.

	   requestUser
	*/
	RequestUser *string

	/* VarianceFormat.

	   varianceFormat
	*/
	VarianceFormat *string

	/* VarianceLevel.

	   varianceLevel
	*/
	VarianceLevel *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update benefit option list description using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithDefaults() *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update benefit option list description using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithTimeout(timeout time.Duration) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithContext(ctx context.Context) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithHTTPClient(client *http.Client) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEffectiveDate adds the effectiveDate to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithEffectiveDate(effectiveDate *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetEffectiveDate(effectiveDate)
	return o
}

// SetEffectiveDate adds the effectiveDate to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetEffectiveDate(effectiveDate *string) {
	o.EffectiveDate = effectiveDate
}

// WithNewChoiceListDescription adds the newChoiceListDescription to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithNewChoiceListDescription(newChoiceListDescription *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetNewChoiceListDescription(newChoiceListDescription)
	return o
}

// SetNewChoiceListDescription adds the newChoiceListDescription to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetNewChoiceListDescription(newChoiceListDescription *string) {
	o.NewChoiceListDescription = newChoiceListDescription
}

// WithOldChoiceListDescription adds the oldChoiceListDescription to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithOldChoiceListDescription(oldChoiceListDescription *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetOldChoiceListDescription(oldChoiceListDescription)
	return o
}

// SetOldChoiceListDescription adds the oldChoiceListDescription to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetOldChoiceListDescription(oldChoiceListDescription *string) {
	o.OldChoiceListDescription = oldChoiceListDescription
}

// WithPolicyNumber adds the policyNumber to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithPolicyNumber(policyNumber *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetPolicyNumber(policyNumber)
	return o
}

// SetPolicyNumber adds the policyNumber to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetPolicyNumber(policyNumber *string) {
	o.PolicyNumber = policyNumber
}

// WithRequestApplication adds the requestApplication to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithRequestApplication(requestApplication *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetRequestApplication(requestApplication *string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithRequestUser(requestUser *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetRequestUser(requestUser *string) {
	o.RequestUser = requestUser
}

// WithVarianceFormat adds the varianceFormat to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithVarianceFormat(varianceFormat *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetVarianceFormat(varianceFormat)
	return o
}

// SetVarianceFormat adds the varianceFormat to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetVarianceFormat(varianceFormat *string) {
	o.VarianceFormat = varianceFormat
}

// WithVarianceLevel adds the varianceLevel to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WithVarianceLevel(varianceLevel *string) *UpdateBenefitOptionListDescriptionUsingPOSTParams {
	o.SetVarianceLevel(varianceLevel)
	return o
}

// SetVarianceLevel adds the varianceLevel to the update benefit option list description using p o s t params
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) SetVarianceLevel(varianceLevel *string) {
	o.VarianceLevel = varianceLevel
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateBenefitOptionListDescriptionUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EffectiveDate != nil {

		// query param effectiveDate
		var qrEffectiveDate string

		if o.EffectiveDate != nil {
			qrEffectiveDate = *o.EffectiveDate
		}
		qEffectiveDate := qrEffectiveDate
		if qEffectiveDate != "" {

			if err := r.SetQueryParam("effectiveDate", qEffectiveDate); err != nil {
				return err
			}
		}
	}

	if o.NewChoiceListDescription != nil {

		// query param newChoiceListDescription
		var qrNewChoiceListDescription string

		if o.NewChoiceListDescription != nil {
			qrNewChoiceListDescription = *o.NewChoiceListDescription
		}
		qNewChoiceListDescription := qrNewChoiceListDescription
		if qNewChoiceListDescription != "" {

			if err := r.SetQueryParam("newChoiceListDescription", qNewChoiceListDescription); err != nil {
				return err
			}
		}
	}

	if o.OldChoiceListDescription != nil {

		// query param oldChoiceListDescription
		var qrOldChoiceListDescription string

		if o.OldChoiceListDescription != nil {
			qrOldChoiceListDescription = *o.OldChoiceListDescription
		}
		qOldChoiceListDescription := qrOldChoiceListDescription
		if qOldChoiceListDescription != "" {

			if err := r.SetQueryParam("oldChoiceListDescription", qOldChoiceListDescription); err != nil {
				return err
			}
		}
	}

	if o.PolicyNumber != nil {

		// query param policyNumber
		var qrPolicyNumber string

		if o.PolicyNumber != nil {
			qrPolicyNumber = *o.PolicyNumber
		}
		qPolicyNumber := qrPolicyNumber
		if qPolicyNumber != "" {

			if err := r.SetQueryParam("policyNumber", qPolicyNumber); err != nil {
				return err
			}
		}
	}

	if o.RequestApplication != nil {

		// query param requestApplication
		var qrRequestApplication string

		if o.RequestApplication != nil {
			qrRequestApplication = *o.RequestApplication
		}
		qRequestApplication := qrRequestApplication
		if qRequestApplication != "" {

			if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
				return err
			}
		}
	}

	if o.RequestUser != nil {

		// query param requestUser
		var qrRequestUser string

		if o.RequestUser != nil {
			qrRequestUser = *o.RequestUser
		}
		qRequestUser := qrRequestUser
		if qRequestUser != "" {

			if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
				return err
			}
		}
	}

	if o.VarianceFormat != nil {

		// query param varianceFormat
		var qrVarianceFormat string

		if o.VarianceFormat != nil {
			qrVarianceFormat = *o.VarianceFormat
		}
		qVarianceFormat := qrVarianceFormat
		if qVarianceFormat != "" {

			if err := r.SetQueryParam("varianceFormat", qVarianceFormat); err != nil {
				return err
			}
		}
	}

	if o.VarianceLevel != nil {

		// query param varianceLevel
		var qrVarianceLevel string

		if o.VarianceLevel != nil {
			qrVarianceLevel = *o.VarianceLevel
		}
		qVarianceLevel := qrVarianceLevel
		if qVarianceLevel != "" {

			if err := r.SetQueryParam("varianceLevel", qVarianceLevel); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
