// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"client/models"
)

// NewUpdatePolicyBenefitOptionsUsingPUTParams creates a new UpdatePolicyBenefitOptionsUsingPUTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePolicyBenefitOptionsUsingPUTParams() *UpdatePolicyBenefitOptionsUsingPUTParams {
	return &UpdatePolicyBenefitOptionsUsingPUTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePolicyBenefitOptionsUsingPUTParamsWithTimeout creates a new UpdatePolicyBenefitOptionsUsingPUTParams object
// with the ability to set a timeout on a request.
func NewUpdatePolicyBenefitOptionsUsingPUTParamsWithTimeout(timeout time.Duration) *UpdatePolicyBenefitOptionsUsingPUTParams {
	return &UpdatePolicyBenefitOptionsUsingPUTParams{
		timeout: timeout,
	}
}

// NewUpdatePolicyBenefitOptionsUsingPUTParamsWithContext creates a new UpdatePolicyBenefitOptionsUsingPUTParams object
// with the ability to set a context for a request.
func NewUpdatePolicyBenefitOptionsUsingPUTParamsWithContext(ctx context.Context) *UpdatePolicyBenefitOptionsUsingPUTParams {
	return &UpdatePolicyBenefitOptionsUsingPUTParams{
		Context: ctx,
	}
}

// NewUpdatePolicyBenefitOptionsUsingPUTParamsWithHTTPClient creates a new UpdatePolicyBenefitOptionsUsingPUTParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePolicyBenefitOptionsUsingPUTParamsWithHTTPClient(client *http.Client) *UpdatePolicyBenefitOptionsUsingPUTParams {
	return &UpdatePolicyBenefitOptionsUsingPUTParams{
		HTTPClient: client,
	}
}

/*
UpdatePolicyBenefitOptionsUsingPUTParams contains all the parameters to send to the API endpoint

	for the update policy benefit options using p u t operation.

	Typically these are written to a http.Request.
*/
type UpdatePolicyBenefitOptionsUsingPUTParams struct {

	/* BenefitOptionList.

	   benefitOptionList
	*/
	BenefitOptionList []*models.PolicyBenefitOptionDTO

	/* EffectiveDate.

	   effectiveDate
	*/
	EffectiveDate *string

	/* RequestApplication.

	   requestApplication
	*/
	RequestApplication *string

	/* RequestUser.

	   requestUser
	*/
	RequestUser *string

	/* VarianceFormat.

	   varianceFormat
	*/
	VarianceFormat *string

	/* VarianceLevel.

	   varianceLevel
	*/
	VarianceLevel *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update policy benefit options using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithDefaults() *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update policy benefit options using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithTimeout(timeout time.Duration) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithContext(ctx context.Context) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithHTTPClient(client *http.Client) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBenefitOptionList adds the benefitOptionList to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithBenefitOptionList(benefitOptionList []*models.PolicyBenefitOptionDTO) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetBenefitOptionList(benefitOptionList)
	return o
}

// SetBenefitOptionList adds the benefitOptionList to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetBenefitOptionList(benefitOptionList []*models.PolicyBenefitOptionDTO) {
	o.BenefitOptionList = benefitOptionList
}

// WithEffectiveDate adds the effectiveDate to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithEffectiveDate(effectiveDate *string) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetEffectiveDate(effectiveDate)
	return o
}

// SetEffectiveDate adds the effectiveDate to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetEffectiveDate(effectiveDate *string) {
	o.EffectiveDate = effectiveDate
}

// WithRequestApplication adds the requestApplication to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithRequestApplication(requestApplication *string) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetRequestApplication(requestApplication)
	return o
}

// SetRequestApplication adds the requestApplication to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetRequestApplication(requestApplication *string) {
	o.RequestApplication = requestApplication
}

// WithRequestUser adds the requestUser to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithRequestUser(requestUser *string) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetRequestUser(requestUser)
	return o
}

// SetRequestUser adds the requestUser to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetRequestUser(requestUser *string) {
	o.RequestUser = requestUser
}

// WithVarianceFormat adds the varianceFormat to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithVarianceFormat(varianceFormat *string) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetVarianceFormat(varianceFormat)
	return o
}

// SetVarianceFormat adds the varianceFormat to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetVarianceFormat(varianceFormat *string) {
	o.VarianceFormat = varianceFormat
}

// WithVarianceLevel adds the varianceLevel to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WithVarianceLevel(varianceLevel *string) *UpdatePolicyBenefitOptionsUsingPUTParams {
	o.SetVarianceLevel(varianceLevel)
	return o
}

// SetVarianceLevel adds the varianceLevel to the update policy benefit options using p u t params
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) SetVarianceLevel(varianceLevel *string) {
	o.VarianceLevel = varianceLevel
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePolicyBenefitOptionsUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.BenefitOptionList != nil {
		if err := r.SetBodyParam(o.BenefitOptionList); err != nil {
			return err
		}
	}

	if o.EffectiveDate != nil {

		// query param effectiveDate
		var qrEffectiveDate string

		if o.EffectiveDate != nil {
			qrEffectiveDate = *o.EffectiveDate
		}
		qEffectiveDate := qrEffectiveDate
		if qEffectiveDate != "" {

			if err := r.SetQueryParam("effectiveDate", qEffectiveDate); err != nil {
				return err
			}
		}
	}

	if o.RequestApplication != nil {

		// query param requestApplication
		var qrRequestApplication string

		if o.RequestApplication != nil {
			qrRequestApplication = *o.RequestApplication
		}
		qRequestApplication := qrRequestApplication
		if qRequestApplication != "" {

			if err := r.SetQueryParam("requestApplication", qRequestApplication); err != nil {
				return err
			}
		}
	}

	if o.RequestUser != nil {

		// query param requestUser
		var qrRequestUser string

		if o.RequestUser != nil {
			qrRequestUser = *o.RequestUser
		}
		qRequestUser := qrRequestUser
		if qRequestUser != "" {

			if err := r.SetQueryParam("requestUser", qRequestUser); err != nil {
				return err
			}
		}
	}

	if o.VarianceFormat != nil {

		// query param varianceFormat
		var qrVarianceFormat string

		if o.VarianceFormat != nil {
			qrVarianceFormat = *o.VarianceFormat
		}
		qVarianceFormat := qrVarianceFormat
		if qVarianceFormat != "" {

			if err := r.SetQueryParam("varianceFormat", qVarianceFormat); err != nil {
				return err
			}
		}
	}

	if o.VarianceLevel != nil {

		// query param varianceLevel
		var qrVarianceLevel string

		if o.VarianceLevel != nil {
			qrVarianceLevel = *o.VarianceLevel
		}
		qVarianceLevel := qrVarianceLevel
		if qVarianceLevel != "" {

			if err := r.SetQueryParam("varianceLevel", qVarianceLevel); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
