// Code generated by go-swagger; DO NOT EDIT.

package cache

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllCacheNamesUsingGETParams creates a new GetAllCacheNamesUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllCacheNamesUsingGETParams() *GetAllCacheNamesUsingGETParams {
	return &GetAllCacheNamesUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllCacheNamesUsingGETParamsWithTimeout creates a new GetAllCacheNamesUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetAllCacheNamesUsingGETParamsWithTimeout(timeout time.Duration) *GetAllCacheNamesUsingGETParams {
	return &GetAllCacheNamesUsingGETParams{
		timeout: timeout,
	}
}

// NewGetAllCacheNamesUsingGETParamsWithContext creates a new GetAllCacheNamesUsingGETParams object
// with the ability to set a context for a request.
func NewGetAllCacheNamesUsingGETParamsWithContext(ctx context.Context) *GetAllCacheNamesUsingGETParams {
	return &GetAllCacheNamesUsingGETParams{
		Context: ctx,
	}
}

// NewGetAllCacheNamesUsingGETParamsWithHTTPClient creates a new GetAllCacheNamesUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllCacheNamesUsingGETParamsWithHTTPClient(client *http.Client) *GetAllCacheNamesUsingGETParams {
	return &GetAllCacheNamesUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetAllCacheNamesUsingGETParams contains all the parameters to send to the API endpoint

	for the get all cache names using g e t operation.

	Typically these are written to a http.Request.
*/
type GetAllCacheNamesUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all cache names using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCacheNamesUsingGETParams) WithDefaults() *GetAllCacheNamesUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all cache names using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCacheNamesUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all cache names using g e t params
func (o *GetAllCacheNamesUsingGETParams) WithTimeout(timeout time.Duration) *GetAllCacheNamesUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all cache names using g e t params
func (o *GetAllCacheNamesUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all cache names using g e t params
func (o *GetAllCacheNamesUsingGETParams) WithContext(ctx context.Context) *GetAllCacheNamesUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all cache names using g e t params
func (o *GetAllCacheNamesUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all cache names using g e t params
func (o *GetAllCacheNamesUsingGETParams) WithHTTPClient(client *http.Client) *GetAllCacheNamesUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all cache names using g e t params
func (o *GetAllCacheNamesUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllCacheNamesUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
